version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each order_id
        columns:
          - name: "(orders_id || '-' || pdt_id)"
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: product
        identifier: raw_gz_product
        description: purchase_price by products_id
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: shipping / logistics per order
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: adwords
        identifier: raw_gz_adwords
        description: Adwords campaigns raw data
        columns:
          - name: "date_date || '--' || campaign_key"
            description: primary key of the table (date + campaign)
            tests:
              - unique
              - not_null

      - name: bing
        identifier: raw_gz_bing
        description: Bing campaigns raw data
        columns:
          - name: "date_date || '--' || campaign_key"
            description: primary key of the table (date + campaign)
            tests:
              - unique
              - not_null

      - name: criteo
        identifier: raw_gz_criteo
        description: Criteo campaigns raw data
        columns:
          - name: "date_date || '--' || campaign_key"
            description: primary key of the table (date + campaign)
            tests:
              - unique
              - not_null

      - name: facebook
        identifier: raw_gz_facebook
        description: Facebook campaigns raw data
        columns:
          - name: "date_date || '--' || campaign_key"
            description: primary key of the table (date + campaign)
            tests:
              - unique
              - not_null
models:
  - name: int_campaigns
    description: "Union of all ad campaign staging tables."
    columns:
      - name: "date_date || '--' || campaign_key || '--' || paid_source"
        description: primary key of the table
        tests:
          - unique
          - not_null

  - name: int_campaigns_day
    description: "Daily aggregation of all ad campaigns."
    columns:
      - name: date
        description: primary key of the table (one row per day)
        tests:
          - unique
          - not_null

  - name: finance_campaigns_day
    description: "Daily finance mart enriched with ad costs."
    columns:
      - name: date
        description: primary key (one row per day)
        tests: [unique, not_null]

